### ISSUE TITLE
mac automated tests - add protobuf package for python 

### ISSUE THREAD

**Issue by barakr** [salilab/npctransport#21]
Ben - there is an issue with some automated tests on most mac builds, I found the problem - just need to add protobuf package for python on relevant machines (eg "pip install protobuf").

**Comment by benmwebb** [comment]
A better option would be to try to import the protobuf module and skip the test if you encounter an `ImportError`. Then users that run the test suite on their own machine will get a more intelligent error message. For example, see how we handle a potentially missing `scipy` modules in the [IMP.isd tests](https://github.com/salilab/imp/blob/develop/modules/isd/test/test_vonMises.py).

Of course, I can also install the protobuf Python module on our Mac build hosts.

**Comment by barakr** [comment]
Good idea to give the more intelligible error message, I will fail the test
nonetheless after giving the message because one shouldn't use the
npctransport module at all (on python) if protobuf is not present.

On Wed, Jun 8, 2016 at 10:23 AM, Ben Webb <notifications@github.com> wrote:

> A better option would be to try to import the protobuf module and skip the
> test if you encounter an ImportError. Then users that run the test suite
> on their own machine will get a more intelligent error message. For
> example, see how we handle a potentially missing scipy modules in the IMP.isd
> tests
> <https://github.com/salilab/imp/blob/develop/modules/isd/test/test_vonMises.py>
> .
>
> Of course, I can also install the protobuf Python module on our Mac build
> hosts.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/salilab/npctransport/issues/21#issuecomment-224665049>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABxMMzDu71klP-23YGpObTFABU5ZMQM6ks5qJvp4gaJpZM4Iwf_1>
> .
>



-- 
Barak

**Comment by barakr** [comment]
Ok fixed - will be good to add the protobuf module to the macs in any case

**Comment by benmwebb** [comment]
Actually our 10.6 and 10.10 machines had it already, and there was only a minor configuration error on 10.11 (it works now). So it must be something a bit more subtle than a failure to `import google.protobuf`.

**Comment by barakr** [comment]
hmm, can I log into the 10.10 machine to test this? (I can't reproduce on
my own mac and it indeed now passes the "import google.protobuf" test on
the auto-build).


On Thu, Jun 16, 2016 at 10:43 PM, Ben Webb <notifications@github.com> wrote:

> Actually our 10.6 and 10.10 machines had it already, and there was only a
> minor configuration error on 10.11 (it works now). So it must be something
> a bit more subtle than a failure to import google.protobuf.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/salilab/npctransport/issues/21#issuecomment-226685300>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABxMM5vTUkgA3Y1yyDOmStp0umWWsSLfks5qMjQFgaJpZM4Iwf_1>
> .
>



-- 
Barak

**Comment by benmwebb** [comment]
> hmm, can I log into the 10.10 machine to test this?

No, sorry, no user accounts on those machines. But I just took a look on 10.10 and I *think* it was failing because the protobuf version there was too old. At least, with an upgrade it seems to be working now.

**Comment by barakr** [comment]
cool thanks.

On Fri, Jun 17, 2016 at 4:29 PM, Ben Webb <notifications@github.com> wrote:

> hmm, can I log into the 10.10 machine to test this?
>
> No, sorry, no user accounts on those machines. But I just took a look on
> 10.10 and I *think* it was failing because the protobuf version there was
> too old. At least, with an upgrade it seems to be working now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/salilab/npctransport/issues/21#issuecomment-226904374>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABxMMyUNgVsAVSOU02IFIWM0fLetlt4Fks5qMy3DgaJpZM4Iwf_1>
> .
>



-- 
Barak

**Comment by benmwebb** [comment]
Should be tested on most Mac platforms these days.
